// packages/refine-vue/src/components/tailwind/inputs/double-date-input.vue
<template>
  <div class="refine-double-date-wrapper">
    <date-picker :date="date1" @input="updateFirstDate" v-bind="$attrs" />
    <p class="refine-double-date-joiner">{{ joiner }}</p>
    <date-picker :date="date2" @input="updateSecondDate" v-bind="$attrs" />
  </div>
</template>

<script>
import DatePicker from './date-picker';

export default {
  name: 'refine-double-date-input',
  components: {
    DatePicker,
  },
  props: {
    date1: {
      type: String,
      required: false,
    },
    date2: {
      type: String,
      required: false,
    },
    joiner: {
      type: String,
      required: false,
      default: 'and',
    },
  },
  methods: {
    updateFirstDate: function ({ date }) {
      this.$emit('input', { date1: date });
    },
    updateSecondDate: function ({ date }) {
      this.$emit('input', { date2: date });
    },
  },
};
</script>

// packages/refine-react/src/components/inputs/double-date/double-date-input.tsx
import React from 'react';
import { FlavorItem, Label, useInput } from 'components';

export const DoubleDateInput = () => {
  const { display, date1, date2, onChange } = useInput<{ date1: string; date2: string }>();

  return (
    <div>
      <Label screenReaderOnly>{display}</Label>
      <FlavorItem<'inputs.date.double.wrapper'> name="inputs.date.double.wrapper">
        <FlavorItem<'inputs.date.double'>
          name="inputs.date.double"
          value={date1}
          onChange={(event) => onChange({ date1: event.target.value })}
        />
        <FlavorItem<'inputs.date.double.joiner'> name="inputs.date.double.joiner">and</FlavorItem>
        <FlavorItem<'inputs.date.double'>
          name="inputs.date.double"
          value={date2}
          onChange={(event) => onChange({ date2: event.target.value })}
        />
      </FlavorItem>
    </div>
  );
};
