// src/components/tailwind/inputs/number-input.vue
<template>
  <input
    class="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md"
    type="text"
    :value="currentValue"
    @input="handleInputChange"
  >
</template>

<script>
 export default {
   data() {
     return {
       currentValue: this.value,
     };
   },
   methods: {
     handleInputChange: function(event) {
       const inputValue = event.target.value;
       const newValue = Number(inputValue);

       if (isNaN(newValue)) {
         // don't emit. Only update with valid inputs so
         // the blueprint won't be updated with garbage and
         // we won't throw proptype errors
         this.currentValue = inputValue;
       } else {
         this.currentValue = newValue;
         this.$emit('input', newValue)
       }

     },
   },
   props: {
     value: {
       type: Number,
       required: false,
     },
   },
 };
</script>

// src/tailwind/components/inputs/number-input.tsx
import { useInput } from "./use-input";

export const NumberInput = () => {
  const { display, value, onChange } = useInput<string>();

  return (
    <div>
      <label className="sr-only">{display}</label>
      <input
        type="number"
        className="bg-white relative w-full border border-gray-300 rounded-md shadow-sm pl-3 pr-10 py-2 text-left cursor-default focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
        value={value}
        onChange={(event) => onChange(event.target.value)}
      />
    </div>
  );
};
