// packages/refine-react/src/tailwind/components/inputs/double-number/double-number-input.tsx
import { Label } from "../../../../components/label";
import { RefineFlavor } from "../../../../components/refine-flavor";
import { useInput } from "../use-input";

export const DoubleNumberInput = () => {
  // TODO: use separate value for each input
  const { display, value, onChange } = useInput<string>();

  return (
    <div>
      <Label screenReaderOnly>{display}</Label>
      <RefineFlavor<"inputs.number.double.wrapper"> name="inputs.number.double.wrapper">
        <RefineFlavor<"inputs.number.double">
          name="inputs.number.double"
          value={value}
          onChange={(event) => onChange(event.target.value)}
        />
        <RefineFlavor<"inputs.number.double.joiner"> name="inputs.number.double.joiner">
          and
        </RefineFlavor>
        <RefineFlavor<"inputs.number.double">
          name="inputs.number.double"
          value={value}
          onChange={(event) => onChange(event.target.value)}
        />
      </RefineFlavor>
    </div>
  );
};

// packages/refine-vue/src/components/tailwind/inputs/double-number-input.vue
<template>
  <refine-flavor as="div" component="inputs.number.double.wrapper">
    <number-input :meta="meta" :value="currentValue" @input="updateFirstValue" />
    <refine-flavor as="span" component="inputs.number.double.joiner" v-if="joinWord">{{
      joinWord
    }}</refine-flavor>
    <number-input :meta="meta" :value="currentValue" @input="updateSecondValue" />
  </refine-flavor>
</template>

<script>
import { RefineFlavor } from '../query-builder/refine-flavor';
import NumberInput from './number-input';

export default {
  name: 'refine-double-number-input',
  data() {
    return {
      currentValue: this.value,
    };
  },
  computed: {
    joinWord() {
      // @TODO Meta helper
      return Object.prototype.hasOwnProperty.call(this.meta, 'joiner') ? this.meta.joiner : 'and';
    },
  },
  methods: {
    updateFirstValue: function ({ value }) {
      this.$emit('input', { value1: value });
    },
    updateSecondValue: function ({ value }) {
      this.$emit('input', { value2: value });
    },
  },
  props: {
    value1: {
      type: [String, Number],
      required: false,
    },
    value2: {
      type: [String, Number],
      required: false,
    },
    meta: {
      type: Object,
      required: false,
      default: () => {
        return {};
      },
    },
  },
  components: {
    NumberInput,
    RefineFlavor,
  },
};
</script>
