// src/components/tailwind/query-builder/query-builder.vue
<template>
  <renderless-query-builder
    :blueprint="blueprint"
    :conditions="conditions"
    v-slot="{
      groupedBlueprint,
      replaceCondition,
      addCriterion,
      addGroup,
      removeCriterion,
      conditionPropsFor,
    }"
  >
    <div class="font-sans">
      <div 
        class="bg-gray-50 p-4 mb-4 rounded"
        v-for="(group, index) in groupedBlueprint" 
        :key="index"
      >
        <div
          v-for="selectedCondition in group"
          :key="selectedCondition.uid"
        >
          <renderless-condition
            v-bind="conditionPropsFor(selectedCondition)"
            v-slot="{
              updateInput,
              condition,
            }"
          >
            <component
              @switch-clause="
                ({id: clause}) => updateInput({ clause })
              "
              @remove-condition="removeCriterion(selectedCondition.position)"
              @switch-condition="
                (nextCondition) =>
                  replaceCondition(condition.uid, conditionPropsFor(nextCondition))
              "
              :is="'ConditionRow'"
              :selectedConditionId="condition.condition_id"
              :conditions="conditions"
              v-bind="{input: condition && {...condition.input}}"
            />
          </renderless-condition>
        </div>
        <button
          @click="addCriterion(group[group.length -1].position)"
          class="background-transparent text-blue-600 text-xs outline-none focus:outline-none flex items-center pt-3"
          type="button"
         >
          <!-- Heroicon name: plus -->
          <svg
            class="h-5 w-5"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 20 20"
            fill="currentColor"
            aria-hidden="true"
          >
            <path
              fill-rule="evenodd"
              d="M10 5a1 1 0 011 1v3h3a1 1 0 110 2h-3v3a1 1 0 11-2 0v-3H6a1 1 0 110-2h3V6a1 1 0 011-1z"
              clip-rule="evenodd"
            />
          </svg>
          <span>And</span>
        </button>
      </div>
      <button
        @click="addGroup"
        type="button" 
        class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
      >
        Add an 'Or'
      </button>
    </div>
    <!-- wrapper div -->
  </renderless-query-builder>
</template>

<script>
import ConditionRow from "./condition-row";
import {
  RenderlessQueryBuilder,
  RenderlessCondition,
} from "@/components/renderless";

export default {
  name: "query-builder",
  props: {
    blueprint: {
      required: false,
      type: Array,
      default: () => {
        return [];
      },
    },
    conditions: {
      required: true,
      type: Array,
    },
  },
  created() {
    if (this.conditions.length === 0) {
      throw new Error(
        "You must provide at least one condition to the query builder."
      );
    }
  },
  components: {
    ConditionRow,
    RenderlessCondition,
    RenderlessQueryBuilder,
  },
};
</script>

// src/tailwind/components/query-builder/query-builder.tsx
import { useState } from "react";
import { Blueprint, Conditions, GroupedBlueprint } from "../../../types";
import { CriterionGroup } from "../criterion-group";
import { QueryBuilderProvider } from "./use-query-builder";

export type QueryBuilderProps = {
  blueprint: Blueprint;
  conditions: Conditions;
};

const groupBlueprintItems = (blueprint: Blueprint): GroupedBlueprint => {
  const groupedBlueprint: GroupedBlueprint = [];
  let currentGroupIndex = 0;

  for (const item of blueprint) {
    if (item.type === "conjunction") {
      if (item.word === "or") {
        currentGroupIndex++;
      }
    }

    if (item.type === "criterion") {
      if (!Array.isArray(groupedBlueprint[currentGroupIndex])) {
        groupedBlueprint.push([]);
      }

      groupedBlueprint[currentGroupIndex].push(item);
    }
  }

  return groupedBlueprint;
};

export const QueryBuilder = ({
  blueprint: initialBlueprint,
  conditions,
}: QueryBuilderProps) => {
  const [groupedBlueprint, setGroupedBlueprint] = useState(() =>
    groupBlueprintItems(initialBlueprint)
  );

  const addGroup = () =>
    setGroupedBlueprint((groupedBlueprint) => [
      ...groupedBlueprint,
      [
        {
          type: "criterion",
          depth: 1,
          condition_id: "option",
          input: { clause: "eq" },
        },
      ],
    ]);

  return (
    <>
      <QueryBuilderProvider
        value={{
          groupedBlueprint,
          updateGroupedBlueprint: setGroupedBlueprint,
          conditions,
        }}
      >
        {groupedBlueprint.map((criteria, index) => (
          <CriterionGroup key={index} criteria={criteria} index={index} />
        ))}
        <button
          type="button"
          onClick={addGroup}
          className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
        >
          Add an 'Or'
        </button>
      </QueryBuilderProvider>
      <pre className="text-xs">{JSON.stringify(groupedBlueprint, null, 2)}</pre>
    </>
  );
};
