// packages/refine-vue/src/components/base/inputs/double-date-input.vue
<template>
  <refine-flavor as='div' component='inputs.date.double.wrapper'>
    <refine-flavor
      as='refine-date-picker'
      component='inputs.date'
      v-bind='$attrs'
      :date='date1'
      @input='e => $emit("input", { date1: e.value })'
    />
    <refine-flavor as='p' component='inputs.date.double.joiner'>{{ joiner }}</refine-flavor>
    <refine-flavor
      as='refine-date-picker'
      component='inputs.date'
      v-bind='$attrs'
      :date='date2'
      @input='e => $emit("input", { date2: e.value })'
    />
  </refine-flavor>
</template>

<script>
import { RefineFlavor } from '../query-builder/refine-flavor';

export default {
  name: 'refine-double-date-input',
  components: {
    RefineFlavor,
  },
  emits: ['input'],
  props: {
    date1: {
      type: String,
      required: false,
    },
    date2: {
      type: String,
      required: false,
    },
    joiner: {
      type: String,
      required: false,
      default: 'and',
    },
  },
};
</script>

// packages/refine-react/src/tailwind/components/inputs/double-date/double-date-input.tsx
import { useInput } from "../use-input";
import { Label } from "../../../../components/label";
import { RefineFlavor } from "../../../../components/refine-flavor";

export const DoubleDateInput = () => {
  // TODO: use separate value for each input
  const { display, value, onChange } = useInput<string>();

  return (
    <div>
      <Label screenReaderOnly>{display}</Label>
      <RefineFlavor<"inputs.date.double.wrapper"> name="inputs.date.double.wrapper">
        <RefineFlavor<"inputs.date.double">
          name="inputs.date.double"
          value={value}
          onChange={(event) => onChange(event.target.value)}
        />
        <RefineFlavor<"inputs.date.double.joiner"> name="inputs.date.double.joiner">
          and
        </RefineFlavor>
        <RefineFlavor<"inputs.date.double">
          name="inputs.date.double"
          value={value}
          onChange={(event) => onChange(event.target.value)}
        />
      </RefineFlavor>
    </div>
  );
};
