// packages/refine-react/src/tailwind/components/inputs/text/text-input.tsx
import { useInput } from "../use-input";

export const TextInput = () => {
  const { display, value, onChange } = useInput<string>();

  return (
    <div>
      <label className="sr-only">{display}</label>
      <input
        type="text"
        className="bg-white relative w-full border border-gray-300 rounded-md shadow-sm pl-3 pr-10 py-2 text-left cursor-default focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
        value={value}
        onChange={(event) => onChange(event.target.value)}
      />
    </div>
  );
};

// src/components/tailwind/inputs/text-input.vue
<template>
  <input
    class="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md"
    type="text"
    :value="value"
    @input="$emit('input', $event.target.value)"
  />
</template>

<script>
 export default {
   props: {
     value: {
       type: String,
       required: true,
     },
   },
 };
</script>
