// examples/vue2/src/App.vue
<template>
  <div>
    <div class="w-max">
      <query-builder 
        :errors="errors"
        :conditions="conditions" 
        v-model="groupedBlueprint" 
        class="p-4 w-100" 
      />
    </div>
    <div>{{ groupedBlueprint }}</div>
  </div>
</template>

<script>
import { QueryBuilder } from "../../../lib/dist/vue2/refine-vue.esm";
import "../../../lib/dist/vue2/refine-vue.esm.css";

const groupedBlueprint = [];

const conditions = [{
  id: "option",
  component: "refine-option-condition",
  display: "Option",
  meta: {
    clauses: [
      {
        id: "in",
        component: "refine-option-input",
        display: "Is One Of",
        meta: { multiple: true },
      },
      {
        id: "eq",
        component: "refine-option-input",
        display: "Is",
        meta: {},
      },
      {
        id: "dne",
        component: "refine-option-input",
        display: "Is Not",
        meta: {},
      },
      {
        id: "nin",
        component: "refine-option-input",
        display: "Is Not One Of",
        meta: { multiple: true },
      },
      {
        id: "st",
        display: "Is Set",
        meta: {},
      },
      {
        id: "nst",
        display: "Is Not Set",
        meta: {},
      },
    ],
    options: [
      {
        id: "foo",
        display: "Foo",
      },
      {
        id: "bar",
        display: "Bar",
      },
      {
        id: "foo2",  
        display: "Foo2",
      },
      {
        id: "bar2",
        display: "Bar2",
      },
    ],
  },
  refinements: [],
},
{
  id: "text",
  display: "Text",
  meta: {
    clauses: [
      {
        id: "eq",
        display: "Equals",
        component: "refine-text-input",
        meta: {},
      },
      {
        id: "dne",
        display: "Does Not Equal",
        component: "refine-text-input",
        meta: {},
      },
      {
        id: "sw",
        display: "Starts With",
        component: "refine-text-input",
        meta: {},
      },
      {
        id: "ew",
        display: "Ends With",
        component: "refine-text-input",
        meta: {},
      },
      {
        id: "dsw",
        display: "Does Not Start With",
        component: "refine-text-input",
        meta: {},
      },
      {
        id: "dew",
        display: "Does Not End With",
        component: "refine-text-input",
        meta: {},
      },
      {
        id: "cont",
        display: "Contains",
        component: "refine-text-input",
        meta: {},
      },
      {
        id: "dcont",
        display: "Does Not Contain",
        component: "refine-text-input",
        meta: {},
      },
      {
        id: "st",
        display: "Is Set",
        meta: {},
      },
      {
        id: "nst",
        display: "Is Not Set",
        meta: {},
      },
    ],
  },
  refinements: [],
},
{
  id: "bool",
  component: "boolean-condition",
  display: "Bool",
  meta: {
    clauses: [
      {
        id: "true",
        display: "Is True",
        meta: {},
      },
      {
        id: "false",
        display: "Is False",
        meta: {},
      },
    ],
  },
  refinements: [],
},
{
  id: "date",
  component: "date-condition",
  display: "Date",
  meta: {
    format: "YYYY/MM/DD",
    clauses: [
      {
        id: "eq",
        display: "Is Equal To",
        component: "refine-date-input",
        meta: {},
      },
      {
        id: "dne",
        display: "Is Not Equal To",
        component: "refine-date-input",
        meta: {},
      },
      {
        id: "lte",
        display: "Is On or Before",
        component: "refine-date-input",
        meta: {},
      },
      {
        id: "gte",
        display: "Is On or After",
        component: "refine-date-input",
        meta: {},
      },
      {
        id: "btwn",
        display: "Is Between",
        component: "refine-double-date-input",
        meta: {},
      },
      {
        id: "gt",
        display: "Is More Than",
        component: "refine-relative-date-input",
        meta: {},
      },
      {
        id: "exct",
        display: "Is Exactly",
        component: "refine-relative-date-input",
        meta: {},
      },
      {
        id: "lt",
        display: "Is Less Than",
        component: "refine-relative-date-input",
        meta: {},
      },
      {
        id: "st",
        display: "Is Set",
        meta: {},
      },
      {
        id: "nst",
        display: "Is Not Set",
        meta: {},
      },
    ],
  },
  refinements: [],
},
{
  id: "date_with_time",
  component: "date-condition",
  display: "Date With Time",
  meta: {
    clauses: [
      {
        id: "eq",
        display: "Is Equal To",
        component: "refine-date-input",
        meta: {},
      },
      {
        id: "dne",
        display: "Is Not Equal To",
        component: "refine-date-input",
        meta: {},
      },
      {
        id: "lte",
        display: "Is On or Before",
        component: "refine-date-input",
        meta: {},
      },
      {
        id: "gte",
        display: "Is On or After",
        component: "refine-date-input",
        meta: {},
      },
      {
        id: "btwn",
        display: "Is Between",
        component: "refine-double-date-input",
        meta: {},
      },
      {
        id: "gt",
        display: "Is More Than",
        component: "refine-relative-date-input",
        meta: {},
      },
      {
        id: "exct",
        display: "Is Exactly",
        component: "refine-relative-date-input",
        meta: {},
      },
      {
        id: "lt",
        display: "Is Less Than",
        component: "refine-relative-date-input",
        meta: {},
      },
      {
        id: "st",
        display: "Is Set",
        meta: {},
      },
      {
        id: "nst",
        display: "Is Not Set",
        meta: {},
      },
    ],
  },
  refinements: [],
},
{
  id: "timestamp",
  component: "date-condition",
  display: "Timestamp",
  meta: {
    clauses: [
      {
        id: "eq",
        display: "Is Equal To",
        component: "refine-date-input",
        meta: {},
      },
      {
        id: "dne",
        display: "Is Not Equal To",
        component: "refine-date-input",
        meta: {},
      },
      {
        id: "lte",
        display: "Is On or Before",
        component: "refine-date-input",
        meta: {},
      },
      {
        id: "gte",
        display: "Is On or After",
        component: "refine-date-input",
        meta: {},
      },
      {
        id: "btwn",
        display: "Is Between",
        component: "refine-double-date-input",
        meta: {},
      },
      {
        id: "gt",
        display: "Is More Than",
        component: "refine-relative-date-input",
        meta: {},
      },
      {
        id: "exct",
        display: "Is Exactly",
        component: "refine-relative-date-input",
        meta: {},
      },
      {
        id: "lt",
        display: "Is Less Than",
        component: "refine-relative-date-input",
        meta: {},
      },
      {
        id: "st",
        display: "Is Set",
        meta: {},
      },
      {
        id: "nst",
        display: "Is Not Set",
        meta: {},
      },
    ],
  },
  refinements: [],
},
{
  id: "numeric",
  component: "numeric-condition",
  display: "Numeric",
  meta: {
    clauses: [        
      {
        id: "eq",
        display: "Is Equal To",
        component: "refine-number-input",
        meta: {},
      },
      {
        id: "dne",
        display: "Is Not Equal To",
        component: "refine-number-input",
        meta: {},
      },
      {
        id: "gt",
        display: "Is Greater Than",
        component: "refine-number-input",
        meta: {},
      },
      {
        id: "gte",
        display: "Is Greater Than Or Equal To",
        component: "refine-number-input",
        meta: {},
      },
      {
        id: "lt",
        display: "Is Less Than",
        component: "refine-number-input",
        meta: {},
      },
      {
        id: "lte",
        display: "Is Less Than Or Equal To",
        component: "refine-number-input",
        meta: {},
      },
      {
        id: "btwn",
        display: "Is Between",
        component: "refine-double-number-input",
        meta: {},
      },
      {
        id: "nbtwn",
        display: "Is Not Between",
        component: "refine-double-number-input",
        meta: {},
      },
      {
        id: "st",
        display: "Is Set",
        meta: {},
      },
      {
        id: "nst",
        display: "Is Not Set",
        meta: {},
      },
    ],
  },
  refinements: [],
},    
{
  "id": "events.name",
  "display": "Events.Name",
  "meta": {
    "clauses": [
      { "id": "eq", "display": "Equals", "meta": {}, "component": "refine-text-input" },
      { "id": "dne", "display": "Does Not Equal", "meta": {}, "component": "refine-text-input" },
      { "id": "sw", "display": "Starts With", "meta": {}, "component": "refine-text-input" },
      { "id": "ew", "display": "Ends With", "meta": {}, "component": "refine-text-input" },
      { "id": "dsw", "display": "Does Not Start With", "meta": {}, "component": "refine-text-input" },
      { "id": "dew", "display": "Does Not End With", "meta": {}, "component": "refine-text-input" },
      { "id": "cont", "display": "Contains", "meta": {}, "component": "refine-text-input" },
      { "id": "dcont", "display": "Does Not Contain", "meta": {}, "component": "refine-text-input" },
      { "id": "st", "display": "Is Set", "meta": {}, "component": "refine-text-input" },
      { "id": "nst", "display": "Is Not Set", "meta": {}, "component": "refine-text-input" }
    ]
  },
  "refinements": [
    {
      "id": "count_refinement",
      "display": "Count Refinement",
      "meta": {
        "clauses": [
          { "id": "eq", "display": "Is Equal To", "meta": {}, "component": "refine-number-input" },
          { "id": "dne", "display": "Is Not Equal To", "meta": {}, "component": "refine-number-input" },
          { "id": "gt", "display": "Is Greater Than", "meta": {}, "component": "refine-number-input" },
          {
            "id": "gte",
            "display": "Is Greater Than Or Equal To",
            "meta": {}, 
            "component": "refine-number-input"
          },
          { "id": "lt", "display": "Is Less Than", "meta": {} },
          {
            "id": "lte",
            "display": "Is Less Than Or Equal To",
            "meta": {}, 
            "component": "refine-number-input"
          },
          { "id": "btwn", "display": "Is Between", "meta": {}, "component": "refine-number-input" },
          { "id": "nbtwn", "display": "Is Not Between", "meta": {}, "component": "refine-number-input" },
          { "id": "st", "display": "Is Set", "meta": {}, "component": "refine-number-input" },
          { "id": "nst", "display": "Is Not Set", "meta": {}, "component": "refine-number-input" }
        ]
      },
      "refinements": []
    }, {
      "id": "kaboom_refinement",
      "display": "Kaboom Refinement",
      "meta": {
        "clauses": [
          { "id": "eq", "display": "Is Equal To", "meta": {}, "component": "refine-number-input" },
          { "id": "dne", "display": "Is Not Equal To", "meta": {}, "component": "refine-number-input" },
          { "id": "gt", "display": "Is Greater Than", "meta": {}, "component": "refine-number-input" },
          {
            "id": "gte",
            "display": "Is Greater Than Or Equal To",
            "meta": {}, 
            "component": "refine-number-input"
          },
          { "id": "lt", "display": "Is Less Than", "meta": {} },
          {
            "id": "lte",
            "display": "Is Less Than Or Equal To",
            "meta": {}, 
            "component": "refine-number-input"
          },
          { "id": "btwn", "display": "Is Between", "meta": {}, "component": "refine-number-input" },
          { "id": "nbtwn", "display": "Is Not Between", "meta": {}, "component": "refine-number-input" },
          { "id": "st", "display": "Is Set", "meta": {}, "component": "refine-number-input" },
          { "id": "nst", "display": "Is Not Set", "meta": {}, "component": "refine-number-input" }
        ]
      },
      refinements: [],
    },
  ]
}
  ];
  
export default {
  name: "App",
  data() {
    return {
      conditions,
      groupedBlueprint,
      errors: {
        0: [{ 
            id: 23434, 
            message: "You messed up big time",
          }, {
            id: 454534,
            message: "Good luck with your life"
          }]
      },
    };
  },
  components: {
    QueryBuilder,
  },
};
</script>

// src/app.tsx
import type { Conditions, Blueprint } from "./types";
import { QueryBuilder } from "./tailwind/components";

const blueprint: Blueprint = [
  {
    depth: 1,
    type: "criterion",
    condition_id: "option",
    input: {
      clause: "eq",
    },
  },
  {
    depth: 1,
    type: "conjunction",
    word: "and",
  },
  {
    depth: 1,
    type: "criterion",
    condition_id: "text",
    input: {
      clause: "eq",
      value: "123",
    },
  },
  {
    depth: 0,
    type: "conjunction",
    word: "or",
  },
  {
    depth: 1,
    type: "criterion",
    condition_id: "numeric",
    input: {
      clause: "eq",
      value: "123",
    },
  },
];

const conditions: Conditions = [
  {
    id: "option",
    component: "OptionCondition",
    display: "Option",
    meta: {
      clauses: [
        {
          id: "in",
          component: "OptionInput",
          display: "Is One Of",
          meta: {
            multiple: true,
          },
        },
        {
          id: "eq",
          component: "OptionInput",
          display: "Is",
          meta: {},
        },
        {
          id: "dne",
          component: "OptionInput",
          display: "Is Not",
          meta: {},
        },
        {
          id: "nin",
          component: "OptionInput",
          display: "Is Not One Of",
          meta: {
            multiple: true,
          },
        },
        {
          id: "st",
          display: "Is Set",
          meta: {},
        },
        {
          id: "nst",
          display: "Is Not Set",
          meta: {},
        },
      ],
      options: [
        {
          id: "foo",
          display: "Foo",
        },
        {
          id: "bar",
          display: "Bar",
        },
        {
          id: "foo2",
          display: "Foo2",
        },
        {
          id: "bar2",
          display: "Bar2",
        },
      ],
    },
    refinements: [],
  },
  {
    id: "text",
    component: "TextCondition",
    display: "Text",
    meta: {
      clauses: [
        {
          id: "eq",
          display: "Equals",
          component: "TextInput",
          meta: {},
        },
        {
          id: "dne",
          display: "Does Not Equal",
          component: "TextInput",
          meta: {},
        },
        {
          id: "sw",
          display: "Starts With",
          component: "TextInput",
          meta: {},
        },
        {
          id: "ew",
          display: "Ends With",
          component: "TextInput",
          meta: {},
        },
        {
          id: "dsw",
          display: "Does Not Start With",
          component: "TextInput",
          meta: {},
        },
        {
          id: "dew",
          display: "Does Not End With",
          component: "TextInput",
          meta: {},
        },
        {
          id: "cont",
          display: "Contains",
          component: "TextInput",
          meta: {},
        },
        {
          id: "dcont",
          display: "Does Not Contain",
          component: "TextInput",
          meta: {},
        },
        {
          id: "st",
          display: "Is Set",
          meta: {},
        },
        {
          id: "nst",
          display: "Is Not Set",
          meta: {},
        },
      ],
    },
    refinements: [],
  },
  {
    id: "bool",
    component: "BooleanCondition",
    display: "Bool",
    meta: {
      clauses: [
        {
          id: "true",
          display: "Is True",
          meta: {},
        },
        {
          id: "false",
          display: "Is False",
          meta: {},
        },
      ],
    },
    refinements: [],
  },
  {
    id: "date",
    component: "DateCondition",
    display: "Date",
    meta: {
      clauses: [
        {
          id: "eq",
          display: "Is Equal To",
          component: "DateInput",
          meta: {},
        },
        {
          id: "dne",
          display: "Is Not Equal To",
          component: "DateInput",
          meta: {},
        },
        {
          id: "lte",
          display: "Is On or Before",
          component: "DateInput",
          meta: {},
        },
        {
          id: "gte",
          display: "Is On or After",
          component: "DateInput",
          meta: {},
        },
        {
          id: "btwn",
          display: "Is Between",
          component: "DoubleDateInput",
          meta: {},
        },
        {
          id: "gt",
          display: "Is More Than",
          component: "RelativeDateInput",
          meta: {},
        },
        {
          id: "exct",
          display: "Is Exactly",
          component: "RelativeDateInput",

          meta: {},
        },
        {
          id: "lt",
          display: "Is Less Than",
          component: "RelativeDateInput",
          meta: {},
        },
        {
          id: "st",
          display: "Is Set",
          meta: {},
        },
        {
          id: "nst",
          display: "Is Not Set",
          meta: {},
        },
      ],
    },
    refinements: [],
  },
  {
    id: "date_with_time",
    component: "DateCondition",
    display: "Date With Time",
    meta: {
      clauses: [
        {
          id: "eq",
          display: "Is Equal To",
          component: "DateInput",
          meta: {},
        },
        {
          id: "dne",
          display: "Is Not Equal To",
          component: "DateInput",
          meta: {},
        },
        {
          id: "lte",
          display: "Is On or Before",
          component: "DateInput",
          meta: {},
        },
        {
          id: "gte",
          display: "Is On or After",
          component: "DateInput",
          meta: {},
        },
        {
          id: "btwn",
          display: "Is Between",
          component: "DoubleDateInput",
          meta: {},
        },
        {
          id: "gt",
          display: "Is More Than",
          component: "RelativeDateInput",
          meta: {},
        },
        {
          id: "exct",
          display: "Is Exactly",
          component: "RelativeDateInput",
          meta: {},
        },
        {
          id: "lt",
          display: "Is Less Than",
          component: "RelativeDateInput",
          meta: {},
        },
        {
          id: "st",
          display: "Is Set",
          meta: {},
        },
        {
          id: "nst",
          display: "Is Not Set",
          meta: {},
        },
      ],
    },
    refinements: [],
  },
  {
    id: "timestamp",
    component: "DateCondition",
    display: "Timestamp",
    meta: {
      clauses: [
        {
          id: "eq",
          display: "Is Equal To",
          component: "DateInput",
          meta: {},
        },
        {
          id: "dne",
          display: "Is Not Equal To",
          component: "DateInput",
          meta: {},
        },
        {
          id: "lte",
          display: "Is On or Before",
          component: "DateInput",
          meta: {},
        },
        {
          id: "gte",
          display: "Is On or After",
          component: "DateInput",
          meta: {},
        },
        {
          id: "btwn",
          display: "Is Between",
          component: "DoubleDateInput",
          meta: {},
        },
        {
          id: "gt",
          display: "Is More Than",
          component: "RelativeDateInput",
          meta: {},
        },
        {
          id: "exct",
          display: "Is Exactly",
          component: "RelativeDateInput",
          meta: {},
        },
        {
          id: "lt",
          display: "Is Less Than",
          component: "RelativeDateInput",
          meta: {},
        },
        {
          id: "st",
          display: "Is Set",
          meta: {},
        },
        {
          id: "nst",
          display: "Is Not Set",
          meta: {},
        },
      ],
    },
    refinements: [],
  },
  {
    id: "numeric",
    component: "NumericCondition",
    display: "Numeric",
    meta: {
      clauses: [
        {
          id: "eq",
          display: "Is Equal To",
          component: "NumberInput",
          meta: {},
        },
        {
          id: "dne",
          display: "Is Not Equal To",
          component: "NumberInput",
          meta: {},
        },
        {
          id: "gt",
          display: "Is Greater Than",
          component: "NumberInput",
          meta: {},
        },
        {
          id: "gte",
          display: "Is Greater Than Or Equal To",
          component: "NumberInput",
          meta: {},
        },
        {
          id: "lt",
          display: "Is Less Than",
          component: "NumberInput",
          meta: {},
        },
        {
          id: "lte",
          display: "Is Less Than Or Equal To",
          component: "NumberInput",
          meta: {},
        },
        {
          id: "btwn",
          display: "Is Between",
          component: "DoubleNumberInput",
          meta: {},
        },
        {
          id: "nbtwn",
          display: "Is Not Between",
          component: "DoubleNumberInput",
          meta: {},
        },
        {
          id: "st",
          display: "Is Set",
          meta: {},
        },
        {
          id: "nst",
          display: "Is Not Set",
          meta: {},
        },
      ],
    },
    refinements: [],
  },
];

const App = () => {
  return <QueryBuilder blueprint={blueprint} conditions={conditions} />;
};

export default App;
