// packages/refine-react/src/tailwind/components/inputs/date/date-input.tsx
import { RefineFlavor } from "../../../../components/refine-flavor";
import { useInput } from "../use-input";

export const DateInput = () => {
  const { display, value, onChange } = useInput<string>();

  return (
    <div>
      <label className="sr-only">{display}</label>
      <RefineFlavor<"inputs.date">
        name="inputs.date"
        value={value}
        onChange={(event) => onChange(event.target.value)}
      />
    </div>
  );
};

// packages/refine-vue/src/components/base/inputs/date-input.vue
<template>
  <refine-flavor
    as='refine-date-picker'
    component='inputs.date'
    v-bind='$attrs'
    :date='date1'
    @input='e => $emit("input", { date1: e.value })'
  />
</template>

<script>
import { RefineFlavor } from '../query-builder/refine-flavor';

export default {
  name: 'refine-date-input',
  components: {
    RefineFlavor
  },
  emits: ['input'],
  props: {
    date1: {
      type: String,
      required: false,
    },
  },
};
</script>
