// packages/refine-react/src/components/inputs/double-date/double-date-input.tsx
import React from 'react';
import { FlavorItem, Label, useInput } from 'components';

export const DoubleDateInput = () => {
  const { display, date1, date2, onChange } = useInput<{ date1: string; date2: string }>();

  return (
    <div>
      <Label screenReaderOnly>{display}</Label>
      <FlavorItem<'inputs.date.double.wrapper'> name="inputs.date.double.wrapper">
        <FlavorItem<'inputs.date.double'>
          name="inputs.date.double"
          value={date1}
          onChange={(event) => onChange({ date1: event.target.value })}
        />
        <FlavorItem<'inputs.date.double.joiner'> name="inputs.date.double.joiner">and</FlavorItem>
        <FlavorItem<'inputs.date.double'>
          name="inputs.date.double"
          value={date2}
          onChange={(event) => onChange({ date2: event.target.value })}
        />
      </FlavorItem>
    </div>
  );
};

// packages/refine-vue/src/components/base/inputs/double-date-input.vue
<template>
  <refine-flavor as='div' component='inputs.date.double.wrapper'>
    <refine-flavor
      as='refine-date-picker'
      component='inputs.date'
      v-bind='$attrs'
      :date='date1'
      @input='e => $emit("input", { date1: e.value })'
    />
    <refine-flavor as='p' component='inputs.date.double.joiner'>{{ joiner }}</refine-flavor>
    <refine-flavor
      as='refine-date-picker'
      component='inputs.date'
      v-bind='$attrs'
      :date='date2'
      @input='e => $emit("input", { date2: e.value })'
    />
  </refine-flavor>
</template>

<script>
import { RefineFlavor } from '../query-builder/refine-flavor';

export default {
  name: 'refine-double-date-input',
  components: {
    RefineFlavor,
  },
  emits: ['input'],
  props: {
    date1: {
      type: String,
      required: false,
    },
    date2: {
      type: String,
      required: false,
    },
    joiner: {
      type: String,
      required: false,
      default: 'and',
    },
  },
};
</script>
