// packages/refine-react/src/components/inputs/text/text-input.tsx
import { FlavorItem, Label, useInput } from "components";

export const TextInput = () => {
  const { display, value, onChange } = useInput<string>();

  return (
    <div>
      <Label screenReaderOnly>{display}</Label>
      <FlavorItem<"inputs.text">
        name="inputs.text"
        value={value}
        onChange={(event) => onChange({ value: event.target.value })}
      />
    </div>
  );
};

// packages/refine-vue/src/components/base/inputs/text-input.vue
<template>
  <refine-flavor
    as="input"
    component="inputs.text"
    type="text"
    :value="value"
    @input="$emit('input', { value: $event.target.value })"
  />
</template>

<script>
import { RefineFlavor } from '../query-builder/refine-flavor';
export default {
  name: 'refine-text-input',
  props: {
    value: {
      type: String,
      required: false,
      default: '',
    },
  },
  components: {
    RefineFlavor,
  },
};
</script>
