// packages/refine-vue/src/components/tailwind/query-builder/criterion.vue
<template>
  <refine-flavor as="div" component="criterion.wrapper">
    <refine-flavor as="ul" component="criterion.errors" v-if="errors.length > 0">
      <refine-flavor
        as="li"
        component="criterion.errors.error"
        v-for="error in errors"
        :key="error.id"
      >
        {{ error.message }}
      </refine-flavor>
    </refine-flavor>

    <refine-flavor
      as="button"
      component="criterion.removeCriterionButton"
      @click.prevent="$emit('remove-condition')"
      type="button"
    >
      <refine-flavor
        as="svg"
        component="criterion.removeCriterionButton.icon"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 20 20"
        fill="currentColor"
      >
        <path
          fill-rule="evenodd"
          d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
          clip-rule="evenodd"
        />
      </refine-flavor>
    </refine-flavor>
    <!-- condition selector -->
    <selector @select-option="switchCondition">
      <selector-option
        v-for="{ id, display, meta, refinements } in conditions"
        :key="id"
        :id="id"
        :display="display"
        :selected="conditionId === id"
      >
        <div>
          <clause :input="input" :meta="meta" @switch-clause="switchClause" />
          <refinements
            v-if="refinements && refinements.length > 0"
            :input="input"
            :refinements="refinements"
          />
        </div>
      </selector-option>
    </selector>
  </refine-flavor>
</template>

<script>
import { Selector, SelectorOption } from '../selector';
import Clause from './clause';
import Refinements from './refinements.vue';
import { RefineFlavor } from './refine-flavor';

export default {
  name: 'criterion',
  props: {
    conditions: {
      required: true,
      type: Array,
    },
    conditionId: {
      type: String,
      required: true,
    },
    input: {
      type: Object,
      required: true,
    },
    errors: {
      type: Array,
      required: false,
      default: () => {
        return [];
      },
    },
  },
  methods: {
    switchCondition: function ({ selectedOption: nextCondition }) {
      this.$emit('switch-condition', nextCondition);
    },
    switchClause: function (nextClause) {
      this.$emit('switch-clause', nextClause);
    },
  },
  components: {
    Clause,
    Refinements,
    SelectorOption,
    Selector,
    RefineFlavor,
  },
};
</script>

// packages/refine-react/src/tailwind/components/criterion/criterion.tsx
import { RefineFlavor } from "../../../components/refine-flavor";
import { Condition } from "../conditions/condition";
import { useCondition } from "../conditions/use-condition";
import { useCriterionGroup } from "../criterion-group/use-criterion-group";
import { useQueryBuilder } from "../query-builder/use-query-builder";
import { CriterionProvider } from "./use-criterion";

export type CriterionProps = {
  index: number;
};

export const Criterion = ({ index }: CriterionProps) => {
  const { blueprint } = useQueryBuilder();
  const { criteria, ...group } = useCriterionGroup();
  const criterion = criteria[index];

  if (!criterion) {
    throw new Error(
      `Could not find criterion index ${index} in group index ${group.index}.`
    );
  }

  const condition = useCondition(criterion.condition_id);

  return (
    <CriterionProvider
      value={{
        updateCondition: (conditionId) =>
          blueprint.replaceCriterion(criterion.position, {
            id: conditionId,
          }),
        updateInput: (input) => blueprint.updateInput(criterion, input),
        ...criterion,
      }}
    >
      <RefineFlavor<"criterion">
        name="criterion"
        data-testid="refine-criterion"
      >
        <RefineFlavor<"criterion.removeCriterionButton">
          name="criterion.removeCriterionButton"
          data-testid="refine-remove-criterion"
          onClick={() => blueprint.removeCriterion(criterion.position)}
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className="h-5 w-5"
            viewBox="0 0 20 20"
            fill="currentColor"
            aria-hidden="true"
          >
            <path
              fillRule="evenodd"
              d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
              clipRule="evenodd"
            />
          </svg>
          <span className="sr-only">Remove Criterion</span>
        </RefineFlavor>
        <Condition condition={condition} />
      </RefineFlavor>
    </CriterionProvider>
  );
};
