// src/components/tailwind/query-builder/criterion.vue
<template>
  <div class="py-2">
    <ul class="list-disc list-inside pb-2">
      <li 
        class="pb-1 px-3 text-red-500" 
        v-for="error in errors"
        :key="error.id"
      >
        {{ error.message }}
      </li>
    </ul>

    <div class="flex items-start">
      <button
        @click.prevent="$emit('remove-condition')"
        type="button"
        class="inline-flex items-center justify-center py-1 px-3 text-gray-500 mr-3 h-9"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-5 w-5"
          viewBox="0 0 20 20"
          fill="currentColor"
        >
          <path
            fill-rule="evenodd"
            d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
            clip-rule="evenodd"
          />
        </svg>
      </button>
      <!-- condition selector -->
      <selector 
        @select-option="switchCondition" 
        innerClass="mr-4"
        class="pr-4 flex items-center"
      >
        <selector-option
          v-for="{ id, display, meta, refinements } in conditions"
          :key="id"
          :id="id"
          :display="display"
          :selected="conditionId === id"
        >
          <div>
            <clause :input="input" :meta="meta" @switch-clause="switchClause" />
            <refinements v-if="refinements && refinements.length > 0" :input="input" :refinements="refinements" />
          </div>
        </selector-option>
      </selector>    
    </div>
  </div>
</template>

<script>
import { Selector, SelectorOption } from "..";
import Clause from './clause';
import Refinements from './refinements.vue';

export default {
  name: "criterion",
  props: {
    conditions: {
      required: true,
      type: Array,
    },
    conditionId: {
      type: String,
      required: true,
    },
    input: {
      type: Object,
      required: true,
    },
    errors: {
      type: Array,
      required: false,
      default: () => { return []; },
    },
  },
  methods: {
    switchCondition: function ({ selectedOption: nextCondition }) {
      this.$emit("switch-condition", nextCondition);
    },
    switchClause: function (nextClause) {
      this.$emit("switch-clause", nextClause);
    },
  },
  components: {
    Clause,
    Refinements,
    SelectorOption,
    Selector,
  },
};
</script>

    Refinements

// packages/refine-react/src/tailwind/components/criterion/criterion.tsx
import { Condition } from "../conditions/condition";
import { useCondition } from "../conditions/use-condition";
import { useCriterionGroup } from "../criterion-group/use-criterion-group";
import { useQueryBuilder } from "../query-builder/use-query-builder";
import { CriterionProvider } from "./use-criterion";

export type CriterionProps = {
  index: number;
};

export const Criterion = ({ index }: CriterionProps) => {
  const { blueprint } = useQueryBuilder();
  const { criteria, ...group } = useCriterionGroup();
  const criterion = criteria[index];

  if (!criterion) {
    throw new Error(
      `Could not find criterion index ${index} in group index ${group.index}.`
    );
  }

  const condition = useCondition(criterion.condition_id);

  return (
    <CriterionProvider
      value={{
        updateCondition: (conditionId) =>
          blueprint.replaceCriterion(criterion.position, {
            id: conditionId,
          }),
        updateInput: (input) => blueprint.updateInput(criterion, input),
        ...criterion,
      }}
    >
      <div
        data-testid="refine-criterion"
        className="flex items-center space-x-3"
      >
        <button
          data-testid="refine-remove-criterion"
          className="inline-flex items-center justify-center py-1 px-3 text-gray-500"
          onClick={() => blueprint.removeCriterion(criterion.position)}
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className="h-5 w-5"
            viewBox="0 0 20 20"
            fill="currentColor"
            aria-hidden="true"
          >
            <path
              fillRule="evenodd"
              d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
              clipRule="evenodd"
            />
          </svg>
          <span className="sr-only">Remove Criterion</span>
        </button>
        <Condition condition={condition} />
      </div>
    </CriterionProvider>
  );
};
